### ISSUE TITLE
Turn on nightly builds?

### ISSUE THREAD

**Issue by jchodera** [openmm/pdbfixer#141] opened 2016-10-07 03:11 UTC
@peastman, it looks like the last time a build was run on `pdbfixer` was 2 months ago. Could you turn on nightly builds via http://nightli.es to make it easier to catch when some of the upstream packages might break something?

**Comment by peastman** [comment] 2024-10-31 16:44
Duplicate of #129.

**Closed by peastman** 2024-10-31 16:44 UTC
